---
- name: Deploy Docker Image to Container
  hosts: all
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: shubhamp194/devops-calculator
        tag: latest
        source: pull

    - name: Create & Start Calculator Docker Container
      docker_container:
        name: devops-calculator-container
        image: shubhamp194/devops-calculator
        state: started
        tty: yes
        interactive: yes
